// packages/react/playground/src/App.tsx
import { useState } from 'react';
import { FieldDataType, defineForm, toTanStackOptions } from '@tgb-form/core';
import { useForm } from '@tanstack/react-form';
import { TgbForm, createReactRendererRegistry, type ReactRendererProps } from '../../src';

const definition = defineForm({
  fields: {
    name: {
      type: FieldDataType.String,
      defaultValue: '',
      label: 'Name',
      description: 'Shown on generated documents.',
      props: { placeholder: 'Ada Lovelace' },
      order: 1,
    },
    email: {
      type: FieldDataType.String,
      defaultValue: '',
      label: 'Email',
      description: 'Used for delivery confirmations.',
      props: { placeholder: 'ada@example.com' },
      order: 2,
    },
    subscribed: {
      type: FieldDataType.Boolean,
      defaultValue: true,
      label: 'Subscribe',
      description: 'Receive product updates.',
      order: 3,
    },
  },
});

const renderers = createReactRendererRegistry({
  byType: {
    [FieldDataType.Boolean]: BooleanRenderer,
    [FieldDataType.String]: TextRenderer,
  },
});

export function App() {
  const [submitted, setSubmitted] = useState<Record<string, unknown> | undefined>();

  const form = useForm({
    ...toTanStackOptions(definition),
    onSubmit({ value }) {
      setSubmitted(value);
    },
  });

  return (
    <main className="app-shell">
      <TgbForm
        className="easy-form"
        definition={definition}
        renderers={renderers}
        instance={form}
      />
      <pre>{JSON.stringify(submitted ?? null, null, 2)}</pre>
    </main>
  );
}

function TextRenderer({ description, field, label, name, props, value }: ReactRendererProps) {
  return (
    <label className="field">
      <span>{label}</span>
      <small>{description}</small>
      <input
        name={name}
        onChange={(event) => field.handleChange(event.currentTarget.value)}
        placeholder={String(props?.placeholder ?? '')}
        value={String(value ?? '')}
      />
    </label>
  );
}

function BooleanRenderer({ description, field, label, name, value }: ReactRendererProps) {
  return (
    <label className="field field-inline">
      <input
        checked={Boolean(value)}
        name={name}
        onChange={(event) => field.handleChange(event.currentTarget.checked)}
        type="checkbox"
      />
      <span>
        {label}
        <small>{description}</small>
      </span>
    </label>
  );
}

// packages/vue/playground/src/App.vue
<script setup lang="ts">
  import { defineComponent, h, ref } from 'vue';
  import { defineForm, FieldDataType, toTanStackOptions } from '@tgb-form/core';
  import { useForm } from '@tanstack/vue-form';
  import { TgbForm, createVueRendererRegistry } from '../../src';

  const submitted = ref('');

  const TextRenderer = defineComponent({
    name: 'TextRenderer',
    props: ['label', 'description', 'props', 'value', 'field'],
    setup(props) {
      return () =>
        h('label', { class: 'field' }, [
          h('span', { class: 'field-label' }, props.label),
          h('input', {
            value: props.value,
            placeholder: props.props?.placeholder,
            onInput: (event: Event) => {
              props.field.handleChange((event.target as HTMLInputElement).value);
            },
            onBlur: props.field.handleBlur,
          }),
          props.description ? h('small', props.description) : null,
        ]);
    },
  });

  const CheckboxRenderer = defineComponent({
    name: 'CheckboxRenderer',
    props: ['label', 'value', 'field'],
    setup(props) {
      return () =>
        h('label', { class: 'field field-checkbox' }, [
          h('input', {
            type: 'checkbox',
            checked: props.value,
            onChange: (event: Event) => {
              props.field.handleChange((event.target as HTMLInputElement).checked);
            },
            onBlur: props.field.handleBlur,
          }),
          h('span', props.label),
        ]);
    },
  });

  const definition = defineForm({
    fields: {
      email: {
        type: FieldDataType.String,
        defaultValue: '',
        label: 'Email',
        description: 'Passed through to a Vue renderer component.',
        props: { placeholder: 'you@example.com' },
      },
      subscribed: {
        type: FieldDataType.Boolean,
        defaultValue: false,
        label: 'Subscribe to updates',
        order: 2,
      },
    },
  });

  const renderers = createVueRendererRegistry({
    byType: {
      [FieldDataType.String]: TextRenderer,
      [FieldDataType.Boolean]: CheckboxRenderer,
    },
  });

  const form = useForm(
    toTanStackOptions(definition, {
      onSubmit({ value }) {
        submitted.value = JSON.stringify(value, null, 2);
      },
    }),
  );
</script>

<template>
  <main>
    <section class="panel">
      <h1>Vue TgbForm Adapter</h1>
      <TgbForm
        :definition="definition"
        :instance="form"
        :renderers="renderers"
      />
      <pre v-if="submitted">{{ submitted }}</pre>
    </section>
  </main>
</template>
