// packages/react/src/MyButton.tsx
import { useState } from 'react';

interface MyButtonProps {
  type?: 'primary';
}

export const MyButton: React.FC<MyButtonProps> = ({ type }) => {
  const [count, setCount] = useState(0);
  return (
    <button
      type="button"
      className="my-button"
      onClick={() => setCount(count + 1)}
    >
      my button
      <br /> type: {type}
      <br /> count: {count}
    </button>
  );
};

// packages/vue/src/MyButton.vue
<script setup lang="ts">
  import { ref } from 'vue';

  const { type } = defineProps<{
    type?: 'primary';
  }>();

  const count = ref(0);
</script>

<template>
  <button
    class="my-button"
    @click="count++"
  >
    my button<br />
    type: {{ type }}<br />
    count: {{ count }}
  </button>
</template>

<style scoped>
  .my-button {
    padding: 8px 16px;
  }
</style>
